# Generated by Django 3.2.25 on 2025-05-12 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('message', models.CharField(max_length=40)),
                ('fromid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kk', to='myapp.login_table')),
                ('toid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mmm', to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.TextField()),
                ('type', models.CharField(default='pending', max_length=40)),
                ('POSTID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.post_table')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('replay', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('feedback', models.CharField(max_length=40)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BigIntegerField()),
                ('date', models.DateField()),
                ('POSTID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.post_table')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('POSTID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.post_table')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('fromid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ll', to='myapp.login_table')),
                ('toid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jjj', to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='theft_alert_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment_table',
            name='POST',
        ),
        migrations.RemoveField(
            model_name='comment_table',
            name='USER',
        ),
        migrations.RemoveField(
            model_name='complaint_table',
            name='USER',
        ),
        migrations.RemoveField(
            model_name='cuberbullying_table',
            name='POST',
        ),
        migrations.RemoveField(
            model_name='feedback_table',
            name='user',
        ),
        migrations.RemoveField(
            model_name='friend_request_table',
            name='FROM',
        ),
        migrations.RemoveField(
            model_name='friend_request_table',
            name='TO',
        ),
        migrations.RemoveField(
            model_name='like_table',
            name='POST',
        ),
        migrations.RemoveField(
            model_name='like_table',
            name='USER',
        ),
        migrations.RemoveField(
            model_name='theftinfo_table',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user_table',
            name='pin',
        ),
        migrations.AddField(
            model_name='theftinfo_table',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theftinfo_table',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='chat_table',
        ),
        migrations.DeleteModel(
            name='comment_table',
        ),
        migrations.DeleteModel(
            name='complaint_table',
        ),
        migrations.DeleteModel(
            name='cuberbullying_table',
        ),
        migrations.DeleteModel(
            name='feedback_table',
        ),
        migrations.DeleteModel(
            name='friend_request_table',
        ),
        migrations.DeleteModel(
            name='like_table',
        ),
        migrations.AddField(
            model_name='theft_alert_table',
            name='Theft_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frm', to='myapp.user_table'),
        ),
        migrations.AddField(
            model_name='theft_alert_table',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usr', to='myapp.user_table'),
        ),
        migrations.AddField(
            model_name='post_alert',
            name='USERNAME',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table'),
        ),
        migrations.AddField(
            model_name='like',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='USERNAME',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='USERNAME',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table'),
        ),
        migrations.AddField(
            model_name='comment',
            name='USERNAME',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table'),
        ),
    ]
