from django.contrib import admin
from django.urls import path

from myapp import views

urlpatterns = [
    path('',views.login,name='login'),
    path('loginpost',views.loginpost,name='loginpost'),
    path('logout',views.logout,name='logout'),
    path('home', views.home, name='home'),
    path('complaint',views.complaint,name='complaint'),
    path('feedback',views.feedback,name='feedback'),
    path('reply_send_get/<id>',views.reply_send_get,name='reply_send_get'),
    path('users',views.users,name= 'users'),
    path('viewtheft',views.viewtheft,name='viewtheft'),
    path('cyberbullying',views.cyberbullying,name='cyberbullying'),
    path('block_users/<id>',views.block_users,name='block_users'),
    path('unblock_users/<id>',views.unblock_users,name='unblock_users'),
    path('reply_send',views.reply_send,name='reply_send'),
    path('and_login',views.and_login,name='and_login'),
    path('viewfriendrequest',views.viewfriendrequest,name='viewfriendrequest'),
    path('sendcomplaint',views.sendcomplaint,name='sendcomplaint'),
    path('viewcomplaintreply',views.viewcomplaintreply,name='viewcomplaintreply'),
    path('viewprofile', views.viewprofile, name='viewprofile'),
    path('/sendfeedback', views.sendfeedback, name='sendfeedback'),
    path('/sendcompalint', views.sendcompalint, name='sendcompalint'),
    path('/viewreply', views.viewreply, name='viewreply'),
    path('and_user_reg', views.and_user_reg, name='and_user_reg'),
    path('/view_profile', views.view_profile, name='view_profile'),
    path('/update_profile', views.update_profile, name='update_profile'),
    path('/viewREQUEST', views.viewREQUEST, name='viewREQUEST'),
    path('/accept_friendrequest', views.accept_friendrequest, name='accept_friendrequest'),
    path('/reject_friendrequest', views.reject_friendrequest, name='reject_friendrequest'),
    path('/viewotheruser', views.viewotheruser, name='viewotheruser'),
    path('/send_friendrequest', views.send_friendrequest, name='send_friendrequest'),
    path('/view_acceptedfriend', views.view_acceptedfriend, name='view_acceptedfriend'),
    path('/user_viewchat', views.user_viewchat, name='user_viewchat'),
    path('/user_sendchat', views.user_sendchat, name='user_sendchat'),
    path('/add_like', views.add_like, name='add_like'),
    path('/viewcomment', views.viewcomment, name='viewcomment'),
    path('/view_my_post', views.view_my_post, name='view_my_post'),
    path('view_my_post', views.view_my_post, name='view_my_post'),
    path('view_likes', views.view_likes, name='view_likes'),
    path('/view_others_post', views.view_others_post, name='view_others_post'),
    path('/add_comment', views.add_comment, name='add_comment'),
    path('/remove_friend', views.remove_friend, name='remove_friend'),
    path('/userchangepass', views.userchangepass, name='userchangepass'),
    path('/delete_post', views.delete_post, name='delete_post'),
    path('add_post', views.add_post, name='add_post'),
    path('view_post_alert', views.view_post_alert, name='view_post_alert'),
    path('rejectPostAlert', views.rejectPostAlert, name='rejectPostAlert'),
    path('/userviewtheft', views.userviewtheft, name='userviewtheft'),
    path('theft_alert_action', views.theft_alert_action, name='theft_alert_action'),
    path('theft_alert_reject', views.theft_alert_reject, name='theft_alert_reject'),
    path('/delete_friendrequest', views.delete_friendrequest, name='delete_friendrequest'),
    path('/block_user', views.block_user, name='block_user'),
    path('/unblock_user', views.unblock_user, name='unblock_user'),
    path('/eachuserpost', views.eachuserpost, name='eachuserpost'),
    path('/send_post', views.send_post, name='send_post'),
    path('post_alert_action', views.post_alert_action, name='post_alert_action'),
    path('/view_acceptedfriendlist', views.view_acceptedfriendlist, name='view_acceptedfriendlist'),
    path('/viewotheruserprofile', views.viewotheruserprofile, name='viewotheruserprofile'),
    path('/view_followinglist', views.view_followinglist, name='view_followinglist'),
    path('/view_followerslist', views.view_followerslist, name='view_followerslist'),
    path('/remove_followers_user', views.remove_followers_user, name='remove_followers_user'),
    # path('/otheruserview_acceptedfriend', views.otheruserview_acceptedfriend, name='otheruserview_acceptedfriend'),
]
